# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            CuratedCode
tagline:          'Random Experiments and Other Findings'
description:      'A web blog for experiments by <a href="http://www.twitter.com/CuratedCode">David Aviles</a>'
url:              http://CuratedCode.com
baseurl:          /

author:
  name:           'David Aviles'
  url:            https://twitter.com/CuratedCode

paginate:         5

# Custom vars
version:          2.1.0       
