# Dependencies
markdown:         kramdown
highlighter:      Rogue
excerpt_separator: "\n\n"
gems: [jekyll-paginate]

# Permalinks
permalink:        pretty



# Setup
title:            CuratedCode
tagline:          'Web Apps, Design, Experiments and Awesome Projects'
description:      'Web Experiments and Awesome Projects'
url:              http://CuratedCode.com
baseurl:          /

author:
  name:           'David Aviles'
  url:            https://twitter.com/davidaviles26

# Pagination - v3 Update
paginate:         5
paginate_path:  "/page:num/"

# Custom vars
linkedin:         https://www.linkedin.com/pub/david-aviles/89/19a/796
github:			  https://www.github.com/davida26       
twitter: 		  https://twitter.com/davidaviles26