# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            CuratedCode
tagline:          'Random Experiments and Other Findings'
description:      'Web Experiments and Other Findings by <a href="http://www.twitter.com/CuratedCode">David Aviles</a>'
url:              http://CuratedCode.com
baseurl:          /

author:
  name:           'David Aviles'
  url:            https://twitter.com/CuratedCode

paginate:         5

# Custom vars
linkedin:         https://www.linkedin.com/pub/david-aviles/89/19a/796
github:			  https://www.github.com/davida26       
