# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            CuratedCode
tagline:          'A Blog of Web Experiments and Other Projects'
description:      'A work in progress of experiments and other findings by David Aviles'
url:              http://CuratedCode.com
baseurl:          /

author:
  name:           'David Aviles'
  url:            https://twitter.com/davidaviles26

paginate:         5

# Custom vars
linkedin:         https://www.linkedin.com/pub/david-aviles/89/19a/796
github:			  https://www.github.com/davida26       
twitter: 		  https://twitter.com/davidaviles26