# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            CuratedCode
tagline:          'Web Apps, Design, Experiments and Awesome Projects'
description:      'Web Experiments and Awesome Projects'
url:              http://CuratedCode.com
baseurl:          /

author:
  name:           'David Aviles'
  url:            https://twitter.com/davidaviles26

# Pagination - v3 Update
paginate:         5
paginate_path:  "/code/page:num/"

# Custom vars
linkedin:         https://www.linkedin.com/pub/david-aviles/89/19a/796
github:			  https://www.github.com/davida26       
twitter: 		  https://twitter.com/davidaviles26